package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.Activity;

import java.util.List;

public interface ActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_list
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_list
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_list
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    int insertSelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_list
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    Activity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_list
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    int updateByPrimaryKeySelective(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_list
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    int updateByPrimaryKey(Activity record);

    List<Activity> getActivityByDateNum(long dateNum);
}