package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.ActivityAnswer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ActivityAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_answer
     *
     * @mbggenerated Fri Jan 06 10:32:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_answer
     *
     * @mbggenerated Fri Jan 06 10:32:53 CST 2017
     */
    int insert(ActivityAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_answer
     *
     * @mbggenerated Fri Jan 06 10:32:53 CST 2017
     */
    int insertSelective(ActivityAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_answer
     *
     * @mbggenerated Fri Jan 06 10:32:53 CST 2017
     */
    ActivityAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_answer
     *
     * @mbggenerated Fri Jan 06 10:32:53 CST 2017
     */
    int updateByPrimaryKeySelective(ActivityAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_activity_answer
     *
     * @mbggenerated Fri Jan 06 10:32:53 CST 2017
     */
    int updateByPrimaryKey(ActivityAnswer record);


    ActivityAnswer selectForUpdate(Integer id);

    List<ActivityAnswer> getActivitieAnswers(@Param("activityID") int activityID);

    void updateAnswerStatus(@Param("id") int id,@Param("status") boolean status,@Param("dwID") String dwID);
}