package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.ConsumePrice;

public interface ConsumePriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    int deleteByPrimaryKey(String consumeType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    int insert(ConsumePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    int insertSelective(ConsumePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    ConsumePrice selectByPrimaryKey(String consumeType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    int updateByPrimaryKeySelective(ConsumePrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    int updateByPrimaryKey(ConsumePrice record);
}