package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.ID;
import org.apache.ibatis.annotations.Param;

public interface IDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    int insert(ID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    int insertSelective(ID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    ID selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    int updateByPrimaryKeySelective(ID record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    int updateByPrimaryKey(ID record);

    ID getChatID();

    int updateChatID(@Param(value = "increasement") int increasement);
}