package online.decentworld.rdb.mapper;

import java.util.List;

import online.decentworld.rdb.entity.LikeRecord;

public interface LikeRecordMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    int insert(LikeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_like
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    int insertSelective(LikeRecord record);
    
    List<LikeRecord> getLikeRecords(String dwID);
}