package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.PartnerCode;
import org.apache.ibatis.annotations.Param;

public interface PartnerCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner_code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner_code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    int insert(PartnerCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner_code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    int insertSelective(PartnerCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner_code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    PartnerCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner_code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    int updateByPrimaryKeySelective(PartnerCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partner_code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    int updateByPrimaryKey(PartnerCode record);


    PartnerCode isCodeExist(@Param(value = "code") String code);



}