package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.PayPassword;

public interface PayPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    int deleteByPrimaryKey(String dwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    int insert(PayPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    int insertSelective(PayPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    PayPassword selectByPrimaryKey(String dwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    int updateByPrimaryKeySelective(PayPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    int updateByPrimaryKey(PayPassword record);
}