package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.TransferHistory;

public interface TransferHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transfer_history
     *
     * @mbggenerated Mon Nov 07 16:21:04 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transfer_history
     *
     * @mbggenerated Mon Nov 07 16:21:04 CST 2016
     */
    int insert(TransferHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transfer_history
     *
     * @mbggenerated Mon Nov 07 16:21:04 CST 2016
     */
    int insertSelective(TransferHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transfer_history
     *
     * @mbggenerated Mon Nov 07 16:21:04 CST 2016
     */
    TransferHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transfer_history
     *
     * @mbggenerated Mon Nov 07 16:21:04 CST 2016
     */
    int updateByPrimaryKeySelective(TransferHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_transfer_history
     *
     * @mbggenerated Mon Nov 07 16:21:04 CST 2016
     */
    int updateByPrimaryKey(TransferHistory record);
}