package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.UserInfo;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Aug 17 15:05:22 CST 2016
     */
    int deleteByPrimaryKey(String dwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Aug 17 15:05:22 CST 2016
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Aug 17 15:05:22 CST 2016
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Aug 17 15:05:22 CST 2016
     */
    UserInfo selectByPrimaryKey(String dwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Aug 17 15:05:22 CST 2016
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Wed Aug 17 15:05:22 CST 2016
     */
    int updateByPrimaryKey(UserInfo record);
}