package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.User;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 04 19:25:44 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 04 19:25:44 CST 2016
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 04 19:25:44 CST 2016
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 04 19:25:44 CST 2016
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 04 19:25:44 CST 2016
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Oct 04 19:25:44 CST 2016
     */
    int updateByPrimaryKey(User record);

    String getUserPassword(@Param("dwID") String dwID);


    String getUserPayPassword(@Param("dwID") String dwID);


    User selectByUnionid(@Param("unionid") String unionid);

    User selectByPhoneNum(@Param("phoneNum") String phoneNum);

    int resetPassword(@Param("phone") String phone,@Param("password") String password);

    void setPayPassword(@Param("id") String dwID,@Param("paypassowrd") String paypassowrd);

    void bindPhoneNum(@Param("phone") String phone,@Param("id") String dwID);

    void bindAccount(@Param("account") String account,@Param("accountType") String accountType,@Param("id") String dwID);
}