package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.VipRecords;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VipRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int deleteByPrimaryKey(String dwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int insert(VipRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int insertSelective(VipRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    VipRecords selectByPrimaryKey(String dwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int updateByPrimaryKeySelective(VipRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_vip_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int updateByPrimaryKey(VipRecords record);


    List<VipRecords> scanVipRecords(@Param(value = "start") int start,@Param(value = "end")int end);
}