package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.WebGame;

public interface WebGameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_game
     *
     * @mbggenerated Wed Mar 08 16:58:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_game
     *
     * @mbggenerated Wed Mar 08 16:58:56 CST 2017
     */
    int insert(WebGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_game
     *
     * @mbggenerated Wed Mar 08 16:58:56 CST 2017
     */
    int insertSelective(WebGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_game
     *
     * @mbggenerated Wed Mar 08 16:58:56 CST 2017
     */
    WebGame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_game
     *
     * @mbggenerated Wed Mar 08 16:58:56 CST 2017
     */
    int updateByPrimaryKeySelective(WebGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_game
     *
     * @mbggenerated Wed Mar 08 16:58:56 CST 2017
     */
    int updateByPrimaryKey(WebGame record);
}