package online.decentworld.rdb.mapper;

import online.decentworld.rdb.entity.WorthChangeRecords;

public interface WorthChangeRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worth_change_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worth_change_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int insert(WorthChangeRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worth_change_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int insertSelective(WorthChangeRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worth_change_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    WorthChangeRecords selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worth_change_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int updateByPrimaryKeySelective(WorthChangeRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worth_change_records
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    int updateByPrimaryKey(WorthChangeRecords record);
}