package online.decentworld.rdb.entity;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_list.id
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_list.img_url
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_list.beginTime
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    private Date begintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_list.endTime
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_list.description
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_list.dateNum
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    private Long datenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_list.id
     *
     * @return the value of t_activity_list.id
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_list.id
     *
     * @param id the value for t_activity_list.id
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_list.img_url
     *
     * @return the value of t_activity_list.img_url
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_list.img_url
     *
     * @param imgUrl the value for t_activity_list.img_url
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_list.beginTime
     *
     * @return the value of t_activity_list.beginTime
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_list.beginTime
     *
     * @param begintime the value for t_activity_list.beginTime
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_list.endTime
     *
     * @return the value of t_activity_list.endTime
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_list.endTime
     *
     * @param endtime the value for t_activity_list.endTime
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_list.description
     *
     * @return the value of t_activity_list.description
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_list.description
     *
     * @param description the value for t_activity_list.description
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_list.dateNum
     *
     * @return the value of t_activity_list.dateNum
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public Long getDatenum() {
        return datenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_list.dateNum
     *
     * @param datenum the value for t_activity_list.dateNum
     *
     * @mbggenerated Wed Jan 04 18:43:44 CST 2017
     */
    public void setDatenum(Long datenum) {
        this.datenum = datenum;
    }
}