package online.decentworld.rdb.entity;

public class ActivityAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_answer.id
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_answer.activityID
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    private Integer activityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_answer.answer
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_answer.checked
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    private Boolean checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_answer.dwID
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_answer.contact
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_activity_answer.gift
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    private String gift;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_answer.id
     *
     * @return the value of t_activity_answer.id
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_answer.id
     *
     * @param id the value for t_activity_answer.id
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_answer.activityID
     *
     * @return the value of t_activity_answer.activityID
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public Integer getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_answer.activityID
     *
     * @param activityid the value for t_activity_answer.activityID
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public void setActivityid(Integer activityid) {
        this.activityid = activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_answer.answer
     *
     * @return the value of t_activity_answer.answer
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_answer.answer
     *
     * @param answer the value for t_activity_answer.answer
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_answer.checked
     *
     * @return the value of t_activity_answer.checked
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public Boolean getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_answer.checked
     *
     * @param checked the value for t_activity_answer.checked
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public void setChecked(Boolean checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_answer.dwID
     *
     * @return the value of t_activity_answer.dwID
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_answer.dwID
     *
     * @param dwid the value for t_activity_answer.dwID
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_answer.contact
     *
     * @return the value of t_activity_answer.contact
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_answer.contact
     *
     * @param contact the value for t_activity_answer.contact
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_activity_answer.gift
     *
     * @return the value of t_activity_answer.gift
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public String getGift() {
        return gift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_activity_answer.gift
     *
     * @param gift the value for t_activity_answer.gift
     *
     * @mbggenerated Fri Jan 06 14:59:17 CST 2017
     */
    public void setGift(String gift) {
        this.gift = gift == null ? null : gift.trim();
    }
}