package online.decentworld.rdb.entity;

public class AppVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.version_id
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    private Integer versionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.app_type
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.version_description
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    private String versionDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.downLoadUrl
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    private String downloadurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.version_name
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    private String versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_version.version_num
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    private Integer versionNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.version_id
     *
     * @return the value of t_version.version_id
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.version_id
     *
     * @param versionId the value for t_version.version_id
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.app_type
     *
     * @return the value of t_version.app_type
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.app_type
     *
     * @param appType the value for t_version.app_type
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.version_description
     *
     * @return the value of t_version.version_description
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public String getVersionDescription() {
        return versionDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.version_description
     *
     * @param versionDescription the value for t_version.version_description
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public void setVersionDescription(String versionDescription) {
        this.versionDescription = versionDescription == null ? null : versionDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.downLoadUrl
     *
     * @return the value of t_version.downLoadUrl
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public String getDownloadurl() {
        return downloadurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.downLoadUrl
     *
     * @param downloadurl the value for t_version.downLoadUrl
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public void setDownloadurl(String downloadurl) {
        this.downloadurl = downloadurl == null ? null : downloadurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.version_name
     *
     * @return the value of t_version.version_name
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.version_name
     *
     * @param versionName the value for t_version.version_name
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_version.version_num
     *
     * @return the value of t_version.version_num
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public Integer getVersionNum() {
        return versionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_version.version_num
     *
     * @param versionNum the value for t_version.version_num
     *
     * @mbggenerated Sat Sep 03 17:30:18 CST 2016
     */
    public void setVersionNum(Integer versionNum) {
        this.versionNum = versionNum;
    }
}