package online.decentworld.rdb.entity;

public class ChatIndex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_index_1.id
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_index_1.dwID
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_index_1.contactID
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    private String contactid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_index_1.is_send
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    private Byte isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_index_1.chat_record_id
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    private Long chatRecordId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_index_1.id
     *
     * @return the value of t_chat_index_1.id
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_index_1.id
     *
     * @param id the value for t_chat_index_1.id
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_index_1.dwID
     *
     * @return the value of t_chat_index_1.dwID
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_index_1.dwID
     *
     * @param dwid the value for t_chat_index_1.dwID
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_index_1.contactID
     *
     * @return the value of t_chat_index_1.contactID
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public String getContactid() {
        return contactid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_index_1.contactID
     *
     * @param contactid the value for t_chat_index_1.contactID
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public void setContactid(String contactid) {
        this.contactid = contactid == null ? null : contactid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_index_1.is_send
     *
     * @return the value of t_chat_index_1.is_send
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public Byte getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_index_1.is_send
     *
     * @param isSend the value for t_chat_index_1.is_send
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public void setIsSend(Byte isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_index_1.chat_record_id
     *
     * @return the value of t_chat_index_1.chat_record_id
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public Long getChatRecordId() {
        return chatRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_index_1.chat_record_id
     *
     * @param chatRecordId the value for t_chat_index_1.chat_record_id
     *
     * @mbggenerated Mon Oct 03 19:16:06 CST 2016
     */
    public void setChatRecordId(Long chatRecordId) {
        this.chatRecordId = chatRecordId;
    }
}