package online.decentworld.rdb.entity;

public class ChatRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_record.mid
     *
     * @mbggenerated Mon Oct 03 20:36:49 CST 2016
     */
    private Long mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chat_record.data
     *
     * @mbggenerated Mon Oct 03 20:36:49 CST 2016
     */
    private byte[] data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_record.mid
     *
     * @return the value of t_chat_record.mid
     *
     * @mbggenerated Mon Oct 03 20:36:49 CST 2016
     */
    public Long getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_record.mid
     *
     * @param mid the value for t_chat_record.mid
     *
     * @mbggenerated Mon Oct 03 20:36:49 CST 2016
     */
    public void setMid(Long mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chat_record.data
     *
     * @return the value of t_chat_record.data
     *
     * @mbggenerated Mon Oct 03 20:36:49 CST 2016
     */
    public byte[] getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chat_record.data
     *
     * @param data the value for t_chat_record.data
     *
     * @mbggenerated Mon Oct 03 20:36:49 CST 2016
     */
    public void setData(byte[] data) {
        this.data = data;
    }
}