package online.decentworld.rdb.entity;

public class ConsumePrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.consume_type
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    private String consumeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_price.price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.consume_type
     *
     * @return the value of t_price.consume_type
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    public String getConsumeType() {
        return consumeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.consume_type
     *
     * @param consumeType the value for t_price.consume_type
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    public void setConsumeType(String consumeType) {
        this.consumeType = consumeType == null ? null : consumeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_price.price
     *
     * @return the value of t_price.price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_price.price
     *
     * @param price the value for t_price.price
     *
     * @mbggenerated Fri Sep 23 11:35:26 CST 2016
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}