package online.decentworld.rdb.entity;

public class CustomAdvice {
	
	
	public enum AdviceType{
		VOICE;
	}
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.advice_id
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    private Integer adviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.advicer
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    private String advicer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.advice_type
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    private String adviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.advice_content
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    private String adviceContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.advice_id
     *
     * @return the value of t_advice.advice_id
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public Integer getAdviceId() {
        return adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.advice_id
     *
     * @param adviceId the value for t_advice.advice_id
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public void setAdviceId(Integer adviceId) {
        this.adviceId = adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.advicer
     *
     * @return the value of t_advice.advicer
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public String getAdvicer() {
        return advicer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.advicer
     *
     * @param advicer the value for t_advice.advicer
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public void setAdvicer(String advicer) {
        this.advicer = advicer == null ? null : advicer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.advice_type
     *
     * @return the value of t_advice.advice_type
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public String getAdviceType() {
        return adviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.advice_type
     *
     * @param adviceType the value for t_advice.advice_type
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public void setAdviceType(String adviceType) {
        this.adviceType = adviceType == null ? null : adviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.advice_content
     *
     * @return the value of t_advice.advice_content
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public String getAdviceContent() {
        return adviceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.advice_content
     *
     * @param adviceContent the value for t_advice.advice_content
     *
     * @mbggenerated Mon Aug 29 09:22:51 CST 2016
     */
    public void setAdviceContent(String adviceContent) {
        this.adviceContent = adviceContent == null ? null : adviceContent.trim();
    }

	public CustomAdvice(String advicer, String adviceType, String adviceContent) {
		super();
		this.advicer = advicer;
		this.adviceType = adviceType;
		this.adviceContent = adviceContent;
	}

	public CustomAdvice() {
		super();
		// TODO Auto-generated constructor stub
	}
    
    
}