package online.decentworld.rdb.entity;

public class FriendContactKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_contact.dwID
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_friend_contact.contact_id
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    private String contactId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_contact.dwID
     *
     * @return the value of t_friend_contact.dwID
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_contact.dwID
     *
     * @param dwid the value for t_friend_contact.dwID
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_friend_contact.contact_id
     *
     * @return the value of t_friend_contact.contact_id
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    public String getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_friend_contact.contact_id
     *
     * @param contactId the value for t_friend_contact.contact_id
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    public void setContactId(String contactId) {
        this.contactId = contactId == null ? null : contactId.trim();
    }
}