package online.decentworld.rdb.entity;

public class ID {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_id.id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_id.chat_id_roof
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    private Long chatIdRoof;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_id.id
     *
     * @return the value of t_id.id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_id.id
     *
     * @param id the value for t_id.id
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_id.chat_id_roof
     *
     * @return the value of t_id.chat_id_roof
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    public Long getChatIdRoof() {
        return chatIdRoof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_id.chat_id_roof
     *
     * @param chatIdRoof the value for t_id.chat_id_roof
     *
     * @mbggenerated Mon Sep 12 17:34:30 CST 2016
     */
    public void setChatIdRoof(Long chatIdRoof) {
        this.chatIdRoof = chatIdRoof;
    }
}