package online.decentworld.rdb.entity;

import java.util.Date;

public class LikeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.recordID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    private Integer recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.dwID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.likedID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    private String likedid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.time
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.recordID
     *
     * @return the value of t_like.recordID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.recordID
     *
     * @param recordid the value for t_like.recordID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.dwID
     *
     * @return the value of t_like.dwID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.dwID
     *
     * @param dwid the value for t_like.dwID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.likedID
     *
     * @return the value of t_like.likedID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public String getLikedid() {
        return likedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.likedID
     *
     * @param likedid the value for t_like.likedID
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public void setLikedid(String likedid) {
        this.likedid = likedid == null ? null : likedid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.time
     *
     * @return the value of t_like.time
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.time
     *
     * @param time the value for t_like.time
     *
     * @mbggenerated Tue Aug 30 16:56:14 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

	public LikeRecord() {
		super();
	}

	public LikeRecord(String dwid, String likedid) {
		super();
		this.dwid = dwid;
		this.likedid = likedid;
		this.time=new Date();
	}
    
    
}