package online.decentworld.rdb.entity;

import java.util.Date;

public class LikeRecord extends LikeRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.time
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.status
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.time
     *
     * @return the value of t_like.time
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.time
     *
     * @param time the value for t_like.time
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.status
     *
     * @return the value of t_like.status
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.status
     *
     * @param status the value for t_like.status
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public LikeRecord(String dwID,String likedID){
        super(dwID,likedID);
        this.time=new Date();
        this.status=RecordStatus.PROCESSING.name();
    }
    public static enum RecordStatus{
        PROCESSING,SUCCESS,FAIL
    }
}