package online.decentworld.rdb.entity;

public class LikeRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.dwID
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_like.likedID
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    private String likedid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.dwID
     *
     * @return the value of t_like.dwID
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.dwID
     *
     * @param dwid the value for t_like.dwID
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_like.likedID
     *
     * @return the value of t_like.likedID
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public String getLikedid() {
        return likedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_like.likedID
     *
     * @param likedid the value for t_like.likedID
     *
     * @mbggenerated Thu Nov 17 16:15:10 CST 2016
     */
    public void setLikedid(String likedid) {
        this.likedid = likedid == null ? null : likedid.trim();
    }

    public LikeRecordKey(String dwid, String likedid) {
        this.dwid = dwid;
        this.likedid = likedid;
    }

    public LikeRecordKey() {

    }
}