package online.decentworld.rdb.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.orderNumer
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private String ordernumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.dwID
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.amount
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.time
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.channel
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.is_paid
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private Boolean isPaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.type
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.extra
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    private String extra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.orderNumer
     *
     * @return the value of t_order.orderNumer
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public String getOrdernumer() {
        return ordernumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.orderNumer
     *
     * @param ordernumer the value for t_order.orderNumer
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setOrdernumer(String ordernumer) {
        this.ordernumer = ordernumer == null ? null : ordernumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.dwID
     *
     * @return the value of t_order.dwID
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.dwID
     *
     * @param dwid the value for t_order.dwID
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.amount
     *
     * @return the value of t_order.amount
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.amount
     *
     * @param amount the value for t_order.amount
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.time
     *
     * @return the value of t_order.time
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.time
     *
     * @param time the value for t_order.time
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.channel
     *
     * @return the value of t_order.channel
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.channel
     *
     * @param channel the value for t_order.channel
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.is_paid
     *
     * @return the value of t_order.is_paid
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public Boolean getIsPaid() {
        return isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.is_paid
     *
     * @param isPaid the value for t_order.is_paid
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setIsPaid(Boolean isPaid) {
        this.isPaid = isPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.type
     *
     * @return the value of t_order.type
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.type
     *
     * @param type the value for t_order.type
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.extra
     *
     * @return the value of t_order.extra
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.extra
     *
     * @param extra the value for t_order.extra
     *
     * @mbggenerated Sat Sep 24 17:53:19 CST 2016
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }
}