package online.decentworld.rdb.entity;

public class PartnerCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.id
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.partner
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    private String partner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.id
     *
     * @return the value of t_partner_code.id
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.id
     *
     * @param id the value for t_partner_code.id
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.code
     *
     * @return the value of t_partner_code.code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.code
     *
     * @param code the value for t_partner_code.code
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.partner
     *
     * @return the value of t_partner_code.partner
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.partner
     *
     * @param partner the value for t_partner_code.partner
     *
     * @mbggenerated Thu Nov 24 18:39:23 CST 2016
     */
    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }
}