package online.decentworld.rdb.entity;

public class PartnerCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.id
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.code
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.partner
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    private String partner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.dwID
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.status
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.partner_type
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    private String partnerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_partner_code.charge_money
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    private Integer chargeMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.id
     *
     * @return the value of t_partner_code.id
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.id
     *
     * @param id the value for t_partner_code.id
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.code
     *
     * @return the value of t_partner_code.code
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.code
     *
     * @param code the value for t_partner_code.code
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.partner
     *
     * @return the value of t_partner_code.partner
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public String getPartner() {
        return partner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.partner
     *
     * @param partner the value for t_partner_code.partner
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public void setPartner(String partner) {
        this.partner = partner == null ? null : partner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.dwID
     *
     * @return the value of t_partner_code.dwID
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.dwID
     *
     * @param dwid the value for t_partner_code.dwID
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.status
     *
     * @return the value of t_partner_code.status
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.status
     *
     * @param status the value for t_partner_code.status
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.partner_type
     *
     * @return the value of t_partner_code.partner_type
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public String getPartnerType() {
        return partnerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.partner_type
     *
     * @param partnerType the value for t_partner_code.partner_type
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public void setPartnerType(String partnerType) {
        this.partnerType = partnerType == null ? null : partnerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_partner_code.charge_money
     *
     * @return the value of t_partner_code.charge_money
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public Integer getChargeMoney() {
        return chargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_partner_code.charge_money
     *
     * @param chargeMoney the value for t_partner_code.charge_money
     *
     * @mbggenerated Sat Dec 24 13:37:19 CST 2016
     */
    public void setChargeMoney(Integer chargeMoney) {
        this.chargeMoney = chargeMoney;
    }

    public static enum Status{
        UNUSED,CHECKED,PAID,REGISTERED
    }

}