package online.decentworld.rdb.entity;

public class PayPassword {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_password.dwID
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_password.pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    private String payPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_password.dwID
     *
     * @return the value of t_pay_password.dwID
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_password.dwID
     *
     * @param dwid the value for t_pay_password.dwID
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_password.pay_password
     *
     * @return the value of t_pay_password.pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    public String getPayPassword() {
        return payPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_password.pay_password
     *
     * @param payPassword the value for t_pay_password.pay_password
     *
     * @mbggenerated Mon Sep 26 15:25:31 CST 2016
     */
    public void setPayPassword(String payPassword) {
        this.payPassword = payPassword == null ? null : payPassword.trim();
    }
}