package online.decentworld.rdb.entity;

import java.util.Date;

public class StrangerContact extends StrangerContactKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stranger_contact.time
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stranger_contact.time
     *
     * @return the value of t_stranger_contact.time
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stranger_contact.time
     *
     * @param time the value for t_stranger_contact.time
     *
     * @mbggenerated Sat Oct 01 18:58:05 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }
}