package online.decentworld.rdb.entity;

import java.util.Date;

public class TipRecords {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tip_records.id
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tip_records.dwID
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tip_records.tiped_userID
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    private String tipedUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tip_records.amount
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tip_records.time
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tip_records.id
     *
     * @return the value of t_tip_records.id
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tip_records.id
     *
     * @param id the value for t_tip_records.id
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tip_records.dwID
     *
     * @return the value of t_tip_records.dwID
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tip_records.dwID
     *
     * @param dwid the value for t_tip_records.dwID
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tip_records.tiped_userID
     *
     * @return the value of t_tip_records.tiped_userID
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public String getTipedUserid() {
        return tipedUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tip_records.tiped_userID
     *
     * @param tipedUserid the value for t_tip_records.tiped_userID
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public void setTipedUserid(String tipedUserid) {
        this.tipedUserid = tipedUserid == null ? null : tipedUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tip_records.amount
     *
     * @return the value of t_tip_records.amount
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tip_records.amount
     *
     * @param amount the value for t_tip_records.amount
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tip_records.time
     *
     * @return the value of t_tip_records.time
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tip_records.time
     *
     * @param time the value for t_tip_records.time
     *
     * @mbggenerated Wed Nov 16 10:14:03 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }


    public TipRecords(String dwid, String tipedUserid, Integer amount) {
        this.dwid = dwid;
        this.tipedUserid = tipedUserid;
        this.amount = amount;
        this.time = new Date();
    }

    public TipRecords() {}
}