package online.decentworld.rdb.entity;

import java.util.Date;

public class TransferHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.id
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.dwID
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.amount
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.status
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.time
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.account_type
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.account
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_transfer_history.ip
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.id
     *
     * @return the value of t_transfer_history.id
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.id
     *
     * @param id the value for t_transfer_history.id
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.dwID
     *
     * @return the value of t_transfer_history.dwID
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.dwID
     *
     * @param dwid the value for t_transfer_history.dwID
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.amount
     *
     * @return the value of t_transfer_history.amount
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.amount
     *
     * @param amount the value for t_transfer_history.amount
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.status
     *
     * @return the value of t_transfer_history.status
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.status
     *
     * @param status the value for t_transfer_history.status
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.time
     *
     * @return the value of t_transfer_history.time
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.time
     *
     * @param time the value for t_transfer_history.time
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.account_type
     *
     * @return the value of t_transfer_history.account_type
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.account_type
     *
     * @param accountType the value for t_transfer_history.account_type
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.account
     *
     * @return the value of t_transfer_history.account
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.account
     *
     * @param account the value for t_transfer_history.account
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_transfer_history.ip
     *
     * @return the value of t_transfer_history.ip
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_transfer_history.ip
     *
     * @param ip the value for t_transfer_history.ip
     *
     * @mbggenerated Tue Nov 08 11:19:08 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();

    }
    public TransferHistory(String dwid, Integer amount, String status,String accountType, String account,String ip) {
        this.dwid = dwid;
        this.amount = amount;
        this.status = status;
        this.time = new Date();
        this.accountType = accountType;
        this.account = account;
        this.ip=ip;
    }
    public TransferHistory(){}
}