package online.decentworld.rdb.entity;

import java.util.Date;

public class VipRecords {
    // 1 exp per second
    public static int ONE_MONTH_EXP=30*24*60*60;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_records.dwID
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    private String dwid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_records.exp
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    private Integer exp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_vip_records.expire
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    private Date expire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_records.dwID
     *
     * @return the value of t_vip_records.dwID
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    public String getDwid() {
        return dwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_records.dwID
     *
     * @param dwid the value for t_vip_records.dwID
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    public void setDwid(String dwid) {
        this.dwid = dwid == null ? null : dwid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_records.exp
     *
     * @return the value of t_vip_records.exp
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_records.exp
     *
     * @param exp the value for t_vip_records.exp
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_vip_records.expire
     *
     * @return the value of t_vip_records.expire
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    public Date getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_vip_records.expire
     *
     * @param expire the value for t_vip_records.expire
     *
     * @mbggenerated Thu Nov 24 18:03:32 CST 2016
     */
    public void setExpire(Date expire) {
        this.expire = expire;
    }
}